title: Blog Bibliotheks- und Archivinformatik
author: Jacqueline
email: jacqueline.kueng@stud.fhgr.ch
description: > # this means to ignore newlines
  Hier folgt mein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2021
  
  
  
# social links
twitter_username: habe kein Twitter # DO NOT include the @ character, or else the build will fail!
github_username:  Schaglin# DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
